# Generated by Django 4.2.11 on 2024-04-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="room_name",
            field=models.CharField(max_length=100, unique=True, verbose_name="채팅방명"),
        ),
    ]
