# Generated by Django 4.2.11 on 2024-04-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_chatroom_room_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatuser",
            constraint=models.UniqueConstraint(
                fields=("user", "chat_room"), name="user_chat_room_unique"
            ),
        ),
    ]
